---
title: "hy2912_p8105_hw3"
author: "Helen Yousaf"
date: "2024-10-07"
output: github_document
---
```{r}
library(readr)
library(tidyverse)
library(ggridges)
```

# Problem 2 
#### MIMS Data

Importing MIMS Demographic data
```{r}
MIMS_dg_df = 
  read_csv(file = "/Users/helenyousaf/Desktop/hy2912_p8105_hw3/MIMS.dg.csv", 
           skip = 4, na = c(".", "NA", ""), 
    col_types = cols(
      'SEQN' = col_character(),
      `sex` = col_character(),
      `age` = col_integer(),
      `BMI` = col_double(),
      `education` = col_character(),
    )
  )
```

```{r}
names(MIMS_dg_df)
MIMS_dg_df = janitor::clean_names(MIMS_dg_df)
```

Importing MIMS Accelerometer data 
```{r}
MIMS_ac_df = 
  read_csv(file = "/Users/helenyousaf/Desktop/hy2912_p8105_hw3/MIMS.ac.csv", 
           na = c(".", "NA", ""), 
     col_types = cols(
      'SEQN' = col_character(),
    )
  )       
```

```{r}
names(MIMS_ac_df)
MIMS_ac_df = janitor::clean_names(MIMS_ac_df)
```

Joining data sets to form MIMS_comb_df
```{r}
MIMS_comb_df = 
  left_join (MIMS_dg_df, MIMS_ac_df, by = "seqn") 
```

```{r}
MIMS_comb_df = 
  drop_na(MIMS_comb_df) |>
  filter ("age" >= 21) |>
  mutate(across(c(sex, education), as.factor)
)
```

Gender and Education Summary Table 
```{r}
gender_ed_df <- MIMS_comb_df |>
  group_by(education, sex) |>
  summarise(count = n()) |>
  pivot_wider(names_from = sex, values_from = count, values_fill = 0)
```

```{r}
gender_ed_df
```
Visualization of the Age-Sex Distribution by Education Level
```{r}
ggplot(MIMS_comb_df, aes(x = age, fill = sex)) +
  geom_histogram(position = "dodge", binwidth = 10, alpha = 0.5) +
  facet_wrap(~ education) +
  labs(title = "Age-Sex Distribution By Education Level",
       x = "Age (years)",
       y = "Count") +
  theme_minimal()
```
